export const SET_GAME_STATE = 'GAME/SET_GAME_STATE';
export const SET_GAME_STATUS = 'GAME/SET_GAME_STATUS';
export const TOGGLE_POPUP = 'APP/TOGGLE_POPUP';
export const TOGGLE_CLICKABLE = 'APP/TOGGLE_CLICKABLE';
